# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
timezone: Asia/Shanghai
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
disqus: littlechoc
google_analytics: UA-80709014-1
title: Littlechoc

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Littlechoc

description: Littlechoc's Blog
author:
  name: Junhao Zhou
  email: junhao.zhou@foxmail.com
  github: junhaozhou
  twitter: zjh1993
  pinterest: junhao_zhou
  linkedin: junhaozhou
  bio: Study in Beijing Institute of Technology since 2011.
  email_md5: f8b015f7fec6ce947dafe298ce3829a1

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

gems:
  - jekyll-paginate